version: '3.8'

services:
  toolwindow-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolwindow_analysis
    working_dir: /toolwindow_analysis
    volumes:
      - .:/toolwindow_analysis
    command: python toolwindow_analysis.py